name: Build and Publish
on:
  push:
    branches: [ 'feat/tests' ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4


      - name: Configura jdk
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          architecture: x64
          cache: maven

      - name: Executar os testes com Maven
        run: mvn test


      - name: Empacotar aplicação com Maven
        run: mvn package -DskipTests


      - name: Guardar artefato em cache
        uses: actions/upload-artifact@v4
        with:
          name: gamelist-api-artifact
          path: application/target

  publish_to_registry:
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Download do artefato
        uses: actions/download-artifact@v4
        with:
          name: gamelist-api-artifact

      - name: Login em Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a5a536ae21d81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Extrai metadata (tags, labels) do Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcd14dcef7be97b2010124a938b7
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/gamelistapi

      - name: Constroi e envia imagem Docker
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d7585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}


      - name: Gera atestado da imagem
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: index.docker.io/${{ secrets.DOCKER_USERNAME }}/gamelistapi
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true








